### PR TITLE
added Readme instructions for contributing

### PR DESCRIPTION
**Pull request by codingfarhan**
Added readme instructions for setting up local repo

### CODE REVIEW

**Comment by shafu0x** [comment]
Thanks!

But I think only `NEXT_PUBLIC_WALLETCONNECT_ID` and `NEXT_PUBLIC_RESERVOIR_API_KEY` are used at this point.

**Comment by codingfarhan** [comment]
This is to avoid run time error mostly, it throws an error when we don't include all of these values
Screenshot 2024-09-08 at 5 20 55 PM

**Comment by codingfarhan** [comment]
@shafu0x Also, strangely enough I had to add these three extra packages in order to make the app work locally. Otherwise it would just throw an error. I haven't pushed these new packages in this PR but just wanted you to know :)

Screenshot 2024-09-08 at 5 25 14 PM

**Comment by shafu0x** [comment]
Interesting. Yeah we definitely need to refactor this.

**Pull request merged**
